/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as NavigateRouteImport } from './routes/navigate'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as IndexRouteImport } from './routes/index'

const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigateRoute = NavigateRouteImport.update({
  id: '/navigate',
  path: '/navigate',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/navigate': typeof NavigateRoute
  '/visits': typeof VisitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/navigate': typeof NavigateRoute
  '/visits': typeof VisitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/navigate': typeof NavigateRoute
  '/visits': typeof VisitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm'
    | '/loading'
    | '/login'
    | '/messages'
    | '/navigate'
    | '/visits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm'
    | '/loading'
    | '/login'
    | '/messages'
    | '/navigate'
    | '/visits'
  id:
    | '__root__'
    | '/'
    | '/confirm'
    | '/loading'
    | '/login'
    | '/messages'
    | '/navigate'
    | '/visits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmRoute: typeof ConfirmRoute
  LoadingRoute: typeof LoadingRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NavigateRoute: typeof NavigateRoute
  VisitsRoute: typeof VisitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigate': {
      id: '/navigate'
      path: '/navigate'
      fullPath: '/navigate'
      preLoaderRoute: typeof NavigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmRoute: ConfirmRoute,
  LoadingRoute: LoadingRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NavigateRoute: NavigateRoute,
  VisitsRoute: VisitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
